### PR TITLE
Add swift version. Issue #4

### PR DESCRIPTION
**Pull request by achernoprudov**
Add swift version to pod spec.

### CODE REVIEW

**Comment by achernoprudov** [comment]
Please update pod in remote repository after merge.
```bash
pod trunk push flutter_device_locale.podspec
```

**Comment by achernoprudov** [comment]
@bratan can you check this PR. Cant build iOS project without this changes.

**Comment by mkuzmentsov** [comment]
Could anybody please take a look at this?

**Comment by achernoprudov** [comment]
Unfortunately fix didn't work out. But I found a workaround. You can set the Swift version by including  `ENV['SWIFT_VERSION'] = '5'` at the top of your `Podfile`.

**Comment by bratan** [comment]
I think there will always be extra steps involved to get swift flutter plugins working. I`m just going to replace swift with objective-c in the next couple of days.

**Comment by achernoprudov** [comment]
In my case problem was in old flutter project written on Objective-C. I updated project to support Swift and now everything works fine. So yes, case was in supporting Swift by project.

But yeah, objc will fix problem. Do you need help with this?

**Pull request merged**
